# Demonstrates the CxFlow++ GH Action running on GH hosted runner and using autobuild
# to execute resolver in an extended container.
name: Execute in autobuild Container on GitHub Hosted Runner
on: 
  workflow_dispatch:


jobs:
  run-action:
    strategy:
      max-parallel: 1
      matrix:
        base_img:
          - "cimg/go:1.22"
          - "golang:1.22-bookworm"
          - "golang:1.22-bullseye"
          - "golang:1.22-alpine"
          - "bitnami/golang:latest"
    permissions:
      security-events: write
    runs-on: ubuntu-latest
    steps:
     
      - name: Fetch Code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
  
      - name: Test CxFlow++
        uses: checkmarx-ts/checkmarx-cxflow-plusplus-github-action@usability
        with:
          sast-log-level: DEBUG
          project-name: $GITHUB_REPOSITORY-${{ matrix.base_img }}-gh-hosted-{branch}
          app-name: $GITHUB_REPOSITORY-${{ matrix.base_img }}
          sast-url: ${{ vars.CX_SAST_URL }}
          sast-username: ${{ secrets.CX_SAST_USERNAME }}
          sast-password: ${{ secrets.CX_SAST_PASSWORD }}
          sca-tenant: ${{ secrets.CX_SCA_TENANT }}
          sca-username: ${{ secrets.CX_SCA_USERNAME }}
          sca-password: ${{ secrets.CX_SCA_PASSWORD }}
          build-container-tag: ${{ matrix.base_img }}

    
          



