# This is an example of an real SDLC workflow config running in a self-hosted runner.
name: SDLC Workflow
on:
    # In this example, scan on push requests to the protected branch.
    push:
        branches: master

        # In this example, scan on pull requests targetting the protected branch.
    pull_request:
        branches: master
    
jobs:
    checkmarx-scan:
        permissions:
            security-events: write
        runs-on: ubuntu-latest
        steps:
          - name: Fetch Code
            uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
        
          - name: Execute Scan
            uses: checkmarx-ts/checkmarx-cxflow-plusplus-github-action@usability
            with:
                sast-log-level: DEBUG
                sast-url: ${{ vars.CX_SAST_URL }}
                sast-username: ${{ secrets.CX_SAST_USERNAME }}
                sast-password: ${{ secrets.CX_SAST_PASSWORD }}
                sca-tenant: ${{ secrets.CX_SCA_TENANT }}
                sca-username: ${{ secrets.CX_SCA_USERNAME }}
                sca-password: ${{ secrets.CX_SCA_PASSWORD }}
                build-container-tag: cimg/go:1.22
