name: SDLC Workflow with CxFlow++
on:
    push:
        branches: master
    pull_request:
        branches: master
    
jobs:
    checkmarx-scan:
        permissions:
        #     security-events: write
            issues: write
            pull-requests: write
        runs-on: ubuntu-latest
        # runs-on: sca-runner
        steps:
          - name: Fetch Code
            uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
        
          - name: Execute Scan
            uses: checkmarx-ts/checkmarx-cxflow-plusplus-github-action@v2
            with:
                sast-log-level: DEBUG
                sast-url: ${{ vars.CX_SAST_URL }}
                sast-username: ${{ secrets.CX_SAST_USERNAME }}
                sast-password: ${{ secrets.CX_SAST_PASSWORD }}
                sca-tenant: ${{ secrets.CX_SCA_TENANT }}
                sca-username: ${{ secrets.CX_SCA_USERNAME }}
                sca-password: ${{ secrets.CX_SCA_PASSWORD }}
                build-container-tag: cimg/go:1.22
                push-feedback-channel: GitHub
                upload-sarif-file: false

